### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by metaodi** [factsmission/dcat-ap-ch-shacl#1]
What is the license of the published SHACL shapes? I'd like to re-use them and need to know if they are actually under an open source license. I'd propose to create a LICENSE.md file to clarify the license of this repository (I think GitHub has support to generate such a file automatically if you specify the license in the settings).

**Comment by metaodi** [comment]
I somehow missed the "License" part of the README (sorry!), it states:

> As prospective part of an eCH standard the code and documentations in this repository can be used, distributed and further developed without any restriction by patents or licenses.

Maybe a LICENSE file might still be worth the effort, as this has good integration with the GitHub user interface. But otherwise this issue can be closed.

**Comment by retog** [comment]
I agree that a license file would be helpful.
